const c=document.querySelector('#canvas'),x=c.getContext('2d'),o=document.querySelector('#overlay'),b=document.querySelector('#start');
let W,H,dpr,fish,pipes,score,best=+localStorage.puffBest||0,run=false,t=0;
function size(){dpr=Math.min(devicePixelRatio||1,2);W=c.clientWidth;H=c.clientHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',size);size();
function reset(){fish={x:W*.28,y:H*.45,v:0,r:23};pipes=[];score=0;t=0;run=true;o.classList.add('hidden')}
function puff(){if(!run)return;fish.v=-6.4}
function pipe(){let gap=Math.max(150,H*.22),top=80+Math.random()*(H-gap-200);pipes.push({x:W+50,top,gap,passed:false})}
function hit(p){return fish.x+fish.r>p.x&&fish.x-fish.r<p.x+62&&(fish.y-fish.r<p.top||fish.y+fish.r>p.top+p.gap)}
function over(){run=false;best=Math.max(best,score);localStorage.puffBest=best;o.innerHTML=`<h1>PUFF RUSH</h1><p>Fim de jogo!<br><b>${score} pontos</b> • Recorde ${best}</p><button id="again">JOGAR DE NOVO</button><small>Toque para voltar ao fundo do mar</small>`;o.classList.remove('hidden');document.querySelector('#again').onclick=reset}
function bg(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#8eeeff');g.addColorStop(1,'#087ba7');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#ffffff55';for(let i=0;i<8;i++){let yy=(i*137+t*.35)%H;x.beginPath();x.arc((i*79)%W,H-yy,4+(i%3)*2,0,7);x.fill()}x.fillStyle='#e7cf79';x.fillRect(0,H-32,W,32)}
function drawFish(){x.save();x.translate(fish.x,fish.y);x.rotate(Math.max(-.35,Math.min(.65,fish.v*.055)));x.fillStyle='#ffe36a';x.beginPath();x.ellipse(0,0,fish.r*1.15,fish.r,0,0,7);x.fill();x.fillStyle='#79d9ef';x.beginPath();x.moveTo(-20,0);x.lineTo(-42,-18);x.lineTo(-38,17);x.closePath();x.fill();x.fillStyle='#fff';x.beginPath();x.arc(10,-7,7,0,7);x.fill();x.fillStyle='#123';x.beginPath();x.arc(13,-7,3,0,7);x.fill();x.strokeStyle='#8b6a22';x.lineWidth=2;x.beginPath();x.arc(9,5,7,.2,2.7);x.stroke();x.restore()}
function drawPipe(p){x.fillStyle='#146b82';x.fillRect(p.x,0,62,p.top);x.fillRect(p.x,p.top+p.gap,62,H-(p.top+p.gap)-32);x.fillStyle='#2ba4ad';x.fillRect(p.x-5,p.top-18,72,18);x.fillRect(p.x-5,p.top+p.gap,72,18)}
function frame(){requestAnimationFrame(frame);bg();if(run){t++;fish.v+=.34;fish.y+=fish.v;if(t%105===0)pipe();for(const p of pipes){p.x-=2.8;drawPipe(p);if(!p.passed&&p.x+62<fish.x){p.passed=true;score++}if(hit(p))over()}pipes=pipes.filter(p=>p.x>-80);if(fish.y-fish.r<0||fish.y+fish.r>H-32)over();drawFish();x.fillStyle='white';x.font='bold 28px Arial';x.textAlign='center';x.fillText(score,W/2,52)}else{fish??={x:W*.28,y:H*.45,v:0,r:23};drawFish()}}
b.onclick=reset;c.addEventListener('pointerdown',puff);addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();run?puff():reset()}});frame();
