const $=q=>document.querySelector(q),C=$("#game"),ctx=C.getContext("2d",{alpha:false});
const screens=["home","map","intro","complete","gameover","premium","ending"];
let W=0,H=0,D=1,last=0,running=false,stage=0,score=0,coins=0,lives=3,distance=0,spawn=0,pickSpawn=0,powerSpawn=0,inv=0,fish,obs=[],items=[],fx=[],bg=0,combo=0,comboT=0;
let best=+(localStorage.pr375finalbest||0),bank=+(localStorage.pr375finalbank||0),unlocked=Math.min(3,+(localStorage.pr375finalunlock||0)),stars=JSON.parse(localStorage.pr375finalstars||"[0,0,0,0]"),premium=false,soundOn=localStorage.pr375sound!=="0";
const STAGES=[
 {name:"RECIFE RASO",short:"RECIFE",icon:"🪸",tier:"FREE",desc:"Aprenda o ritmo em um percurso mais longo e progressivo.",mission:"Chegue ao final • preserve vidas • colete moedas",goal:64,gap:.27,speed:2.45,maxSpeed:3.20,mechanic:"coral",colors:["#6ae7f1","#087ca2"]},
 {name:"CAVERNA",short:"CAVERNA",icon:"💎",tier:"FREE",desc:"Mais longa, mais rápida e com obstáculos móveis.",mission:"Atravesse a caverna • adapte-se à aceleração",goal:76,gap:.245,speed:3.05,maxSpeed:4.10,mechanic:"cave",colors:["#234c86","#160d43"]},
 {name:"NAVIO AFUNDADO",short:"NAVIO",icon:"⚓",tier:"PREMIUM",desc:"Puff Prime entra nos destroços e enfrenta correnteza.",mission:"Passe pelo casco • domine a velocidade",goal:88,gap:.225,speed:3.20,maxSpeed:4.30,mechanic:"ship",colors:["#247e92","#062b46"]},
 {name:"ABISMO",short:"ABISMO",icon:"🌌",tier:"PREMIUM",desc:"A fase final: escura, longa, rápida e precisa.",mission:"Conquiste o Abismo • finalize a jornada",goal:102,gap:.21,speed:3.55,maxSpeed:4.85,mechanic:"abyss",colors:["#102f72","#030817"]}
];
function resize(){D=Math.min(devicePixelRatio||1,2);W=C.clientWidth;H=C.clientHeight;C.width=W*D;C.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener("resize",resize,{passive:true});resize();
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let ac=null,musicTimer=null;function audio(){if(!soundOn)return null;if(!ac)ac=new (window.AudioContext||window.webkitAudioContext)();if(ac.state==="suspended")ac.resume();return ac}function tone(f=440,d=.08,type="sine",v=.025,delay=0){let a=audio();if(!a)return;let o=a.createOscillator(),g=a.createGain(),t=a.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+d)}function sfx(k){if(k==="flap")tone(330,.045,"sine",.014);if(k==="coin"){tone(760,.06,"sine",.025);tone(1050,.07,"sine",.018,.035)}if(k==="hit")tone(110,.15,"sawtooth",.03);if(k==="win")[523,659,784,1047].forEach((n,i)=>tone(n,.2,"triangle",.03,i*.1));if(k==="unlock")[330,440,660,880].forEach((n,i)=>tone(n,.22,"triangle",.025,i*.1))}function musicStart(){musicStop();if(!soundOn)return;let seq=stage<2?[220,277,330,277]:[147,196,220,294],i=0;musicTimer=setInterval(()=>{if(running)tone(seq[i++%seq.length],.25,"sine",.006)},420)}function musicStop(){clearInterval(musicTimer);musicTimer=null}

function screen(id){screens.forEach(s=>$("#"+s).classList.toggle("hidden",s!==id));$("#hud").classList.add("hidden")}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1000)}
function persist(){localStorage.pr375finalbest=Math.max(best,score);localStorage.pr375finalbank=bank;localStorage.pr375finalunlock=unlocked;localStorage.pr375finalstars=JSON.stringify(stars);localStorage.pr375premium="0";localStorage.pr375sound=soundOn?"1":"0";best=Math.max(best,score)}
function homeStats(){}
function mapDraw(){let h="";STAGES.forEach((s,i)=>{let paid=i>=2,lock=i>unlocked||(paid&&!premium);h+=`<div class="stageCard ${paid?"paid":""} ${lock?"locked":""}" data-i="${i}"><span class="medal">${"⭐".repeat(stars[i])}</span><div class="ico">${s.icon}${lock?" 🔒":""}</div><b>${i+1}. ${s.name}</b><small>${s.tier} • ${s.desc}</small></div>`});$("#stageCards").innerHTML=h;document.querySelectorAll(".stageCard").forEach(e=>e.onclick=()=>{let i=+e.dataset.i;if(i>=2&&!premium){screen("premium");return}if(i<=unlocked)intro(i)})}
function intro(i){if(i>=2&&!premium){screen("premium");return}stage=i;let s=STAGES[i];$("#introIcon").textContent=s.icon;$("#introTitle").textContent=s.name;$("#introDesc").textContent=s.desc;$("#introMission").textContent="MISSÃO • "+s.mission;let b=$("#tierBadge");b.textContent=s.tier;b.className="tier "+(i>=2?"paid":"");screen("intro")}
function resetStage(){let s=STAGES[stage];score=0;coins=0;lives=3;distance=0;spawn=45;pickSpawn=55;powerSpawn=300;inv=0;combo=0;obs=[];items=[];fx=[];fish={x:W*.24,y:H*.45,v:0,r:21};running=true;screens.forEach(q=>$("#"+q).classList.add("hidden"));$("#hud").classList.remove("hidden");sync();musicStart()}
function sync(){let s=STAGES[stage];$("#stageName").textContent=s.short;$("#score").textContent=score;$("#coins").textContent=coins;$("#lives").textContent=lives;$("#progress").textContent=Math.min(100,Math.floor(distance/s.goal*100))+"%"}
function speed(){let s=STAGES[stage],p=Math.min(1,distance/s.goal);return s.speed+(s.maxSpeed-s.speed)*p}
function flap(){if(!running)return;audio();sfx("flap");fish.v=-6.15;for(let i=0;i<5;i++)fx.push({x:fish.x-18,y:fish.y+rnd(-8,8),vx:rnd(-2.2,-.6),vy:rnd(-.8,.8),life:1})}
function addObs(){let s=STAGES[stage],gap=Math.max(128,H*s.gap),top=rnd(75,Math.max(85,H-gap-145));obs.push({x:W+70,top,gap,w:rnd(58,73),passed:false,t:rnd(0,6),wob:stage?rnd(2,stage*4+3):0})}
function addItem(type="coin"){items.push({type,x:W+35,y:rnd(90,H-105),r:type==="coin"?9:13,t:rnd(0,6)})}
function hit(o){let top=o.top+Math.sin(o.t)*o.wob;return fish.x+fish.r-5>o.x&&fish.x-fish.r+5<o.x+o.w&&(fish.y-fish.r+5<top||fish.y+fish.r-5>top+o.gap)}
function damage(){if(inv>0)return;sfx("hit");lives--;inv=100;combo=0;toast(lives?"💥 CUIDADO!":"💥 FIM DA TENTATIVA");sync();if(lives<=0)fail()}
function fail(){running=false;musicStop();bank+=coins;persist();$("#gameoverText").innerHTML=`Você chegou a <b>${Math.floor(distance/STAGES[stage].goal*100)}%</b> de ${STAGES[stage].name}.<br>Moedas salvas: <b>${coins}</b>.`;screen("gameover")}
function finish(){running=false;musicStop();sfx("win");let s=STAGES[stage],rating=lives===3&&coins>=8?3:lives>=2?2:1;stars[stage]=Math.max(stars[stage],rating);bank+=coins;if(stage===0)unlocked=Math.max(unlocked,1);if(stage===2)unlocked=Math.max(unlocked,3);persist();$("#completeTitle").textContent=s.name;$("#stars").textContent="★".repeat(rating)+"☆".repeat(3-rating);$("#completeText").innerHTML=`<b>${score} pontos</b> · ${coins} moedas · ${lives} vida${lives!==1?"s":""}<br>${rating===3?"PERFEITO! Você dominou esta fase.":"Fase vencida. A jornada continua."}`;$("#nextStage").textContent=stage===1?"ENTRAR NA ÁREA VIP":stage===3?"VER FINAL":"PRÓXIMA FASE";screen("complete")}
function update(dt){if(!running)return;let s=STAGES[stage];fish.v+=.335*dt;fish.y+=fish.v*dt;if(stage===2)fish.y+=Math.sin(bg*.02)*.22*dt;spawn-=dt;pickSpawn-=dt;powerSpawn-=dt;inv=Math.max(0,inv-dt);comboT-=dt;if(comboT<=0)combo=0;
 if(spawn<=0){addObs();spawn=Math.max(60,100-stage*8)}
 if(pickSpawn<=0){addItem("coin");pickSpawn=rnd(62,105)}
 if(powerSpawn<=0){addItem("shield");powerSpawn=rnd(320,450)}
 let sp=speed()*dt;distance+=sp*.0085; if(distance>=s.goal){finish();return}
 for(const o of obs){o.x-=sp;o.t+=.028*dt;if(!o.passed&&o.x+o.w<fish.x){o.passed=true;score+=2;combo++;comboT=150;if(combo===5){score+=3;combo=0;toast("⚡ COMBO +3")}sync()}if(hit(o))damage()}
 for(const p of items){p.x-=sp*.92;p.t+=.07*dt;if(Math.hypot(p.x-fish.x,p.y-fish.y)<fish.r+p.r){p.dead=true;if(p.type==="coin"){coins++;score++;sfx("coin");if(coins%5===0)toast("🪙 SEQUÊNCIA DE MOEDAS!")}else{inv=330;toast("🛡️ ESCUDO ATIVO")}sync()}}
 obs=obs.filter(o=>o.x>-100);items=items.filter(p=>!p.dead&&p.x>-30);for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=.035*dt}fx=fx.filter(p=>p.life>0);
 if(fish.y-fish.r<0||fish.y+fish.r>H-27){damage();fish.y=clamp(fish.y,fish.r+3,H-51);fish.v=0}
 sync()
}
function background(){let s=STAGES[stage],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,s.colors[0]);g.addColorStop(1,s.colors[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);bg+=speed()*.32;
 ctx.globalAlpha=.14;ctx.fillStyle="#fff";for(let i=0;i<14;i++){let bx=(i*91+bg*.14)%W,by=H-((i*79+bg*(.35+i%3*.1))%H);ctx.beginPath();ctx.arc(bx,by,2+i%4,0,7);ctx.fill()}ctx.globalAlpha=1;
 if(stage===0){ctx.fillStyle="#16a985";for(let i=0;i<8;i++){let q=(i*90-bg*.5)%W;ctx.fillRect(q,H-66,5,40);ctx.beginPath();ctx.arc(q+3,H-68,11,0,7);ctx.fill()}ctx.fillStyle="#e1c674";ctx.fillRect(0,H-27,W,27)}
 if(stage===1){ctx.globalAlpha=.28;ctx.fillStyle="#8a63ff";for(let i=0;i<7;i++){let q=(i*105-bg*.25)%W;ctx.beginPath();ctx.moveTo(q,H);ctx.lineTo(q+20,H-95-(i%3)*20);ctx.lineTo(q+42,H);ctx.fill()}ctx.globalAlpha=1}
 if(stage===2){ctx.strokeStyle="#09283b";ctx.lineWidth=9;ctx.globalAlpha=.7;for(let i=0;i<5;i++){let q=(i*145-bg*.4)%W;ctx.beginPath();ctx.moveTo(q,0);ctx.lineTo(q-75,190);ctx.stroke()}ctx.fillStyle="#573d27";ctx.fillRect((W-bg*.55)%(W+240)-120,H-75,120,18);ctx.globalAlpha=1}
 if(stage===3){ctx.globalAlpha=.22;ctx.fillStyle="#5b7cff";for(let i=0;i<7;i++){let q=(i*110-bg*.18)%W;ctx.beginPath();ctx.arc(q,H*.2+(i%4)*110,30+i*7,0,7);ctx.fill()}ctx.globalAlpha=1}
}
function drawObs(o){let top=o.top+Math.sin(o.t)*o.wob,g=ctx.createLinearGradient(o.x,0,o.x+o.w,0);let mid=stage===3?"#8edbed":stage===1?"#7354b7":"#187f8d";g.addColorStop(0,"#07384e");g.addColorStop(.5,mid);g.addColorStop(1,"#052b43");ctx.fillStyle=g;ctx.fillRect(o.x,0,o.w,top);ctx.fillRect(o.x,top+o.gap,o.w,H-top-o.gap-27);ctx.fillStyle=stage===3?"#d8f8ff":"#36b7ad";ctx.fillRect(o.x-4,top-13,o.w+8,13);ctx.fillRect(o.x-4,top+o.gap,o.w+8,13)}
function drawItem(p){ctx.save();ctx.translate(p.x,p.y);let k=1+Math.sin(p.t)*.12;ctx.scale(k,k);ctx.shadowBlur=18;ctx.shadowColor=p.type==="coin"?"#ffe35b":"#92f6ff";ctx.fillStyle=p.type==="coin"?"#ffd43c":"#a7f7ff";ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.fillStyle="#fff8";ctx.beginPath();ctx.arc(-3,-3,p.r*.28,0,7);ctx.fill();ctx.restore()}
function drawFish(){ctx.save();ctx.translate(fish.x,fish.y);ctx.rotate(clamp(fish.v*.05,-.3,.55));ctx.globalAlpha=inv>0&&Math.floor(inv/8)%2?.5:1;let prime=stage>=2,cave=stage===1;ctx.fillStyle=prime?"#2f82df":cave?"#246eb8":"#70d9ec";ctx.beginPath();ctx.moveTo(-17,0);ctx.lineTo(-42,-16);ctx.lineTo(-37,17);ctx.closePath();ctx.fill();ctx.fillStyle=prime?"#175ab7":cave?"#18549a":"#ffe264";ctx.beginPath();ctx.ellipse(0,0,27,22,0,0,7);ctx.fill();ctx.strokeStyle=cave?"#9fd8ff":"#d5ae24";ctx.lineWidth=cave?2.6:2;for(let a=0;a<6;a++){let q=a*Math.PI/3,spike=cave?36:30;ctx.beginPath();ctx.moveTo(Math.cos(q)*20,Math.sin(q)*16);ctx.lineTo(Math.cos(q)*spike,Math.sin(q)*(cave?29:24));ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(10,-7,7,0,7);ctx.fill();ctx.fillStyle="#082b3d";ctx.beginPath();ctx.arc(13,-7,3,0,7);ctx.fill();ctx.strokeStyle="#8d6815";ctx.beginPath();ctx.arc(9,6,7,.1,2.8);ctx.stroke();if(inv>120){ctx.strokeStyle="#b7f7ff";ctx.lineWidth=3;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(0,0,35,0,7);ctx.stroke()}ctx.restore()}
function render(){background();for(const o of obs)drawObs(o);for(const p of items)drawItem(p);for(const p of fx){ctx.globalAlpha=p.life;ctx.fillStyle="#d8fbff";ctx.beginPath();ctx.arc(p.x,p.y,3,0,7);ctx.fill();ctx.globalAlpha=1}drawFish()}
function loop(t){let dt=Math.min(2,(t-last)/16.667||1);last=t;update(dt);render();requestAnimationFrame(loop)}
$("#continueBtn").onclick=()=>intro(0);$("#mapBtn").onclick=()=>{mapDraw();screen("map")};$("#mapBack").onclick=()=>screen("home");$("#startStage").onclick=resetStage;$("#retry").onclick=resetStage;$("#goMap").onclick=()=>{mapDraw();screen("map")};$("#retryStage").onclick=resetStage;$("#nextStage").onclick=()=>{if(stage===1)screen("premium");else if(stage===3)screen("ending");else intro(stage+1)};$("#premiumHome").onclick=()=>screen("home");$("#premiumPreview").onclick=()=>{audio();sfx("unlock");toast("🔒 ÁREA VIP • EM BREVE")};$("#endingHome").onclick=()=>screen("home");$("#soundBtn").onclick=()=>{soundOn=!soundOn;if(!soundOn)musicStop();persist();$("#soundBtn").textContent=soundOn?"🔊 SOM":"🔇 SOM";if(soundOn)tone(660,.08,"sine",.025)};
C.addEventListener("pointerdown",flap,{passive:true});addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();flap()}});
document.addEventListener("visibilitychange",()=>{if(document.hidden&&running){running=false;bank+=coins;persist();$("#gameoverText").innerHTML="Jogo pausado e moedas salvas.<br>Volte quando quiser.";screen("gameover")}});
fish={x:W*.24,y:H*.45,v:0,r:21};$("#soundBtn").textContent=soundOn?"🔊 SOM":"🔇 SOM";mapDraw();requestAnimationFrame(loop);