const $=q=>document.querySelector(q),C=$("#game"),ctx=C.getContext("2d",{alpha:false});
const screens=["home","map","intro","complete","gameover","premium","ending"];
let W=0,H=0,D=1,last=0,running=false,stage=0,score=0,coins=0,lives=3,distance=0,spawn=0,pickSpawn=0,powerSpawn=0,inv=0,fish,obs=[],items=[],fx=[],bg=0,combo=0,comboT=0;
let best=+(localStorage.pr375best||0),bank=+(localStorage.pr375bank||0),unlocked=Math.min(3,+(localStorage.pr375unlock||0)),stars=JSON.parse(localStorage.pr375stars||"[0,0,0,0]"),premium=localStorage.pr375premium==="1",soundOn=localStorage.pr375sound!=="0";
const STAGES=[
{name:"RECIFE RASO",short:"RECIFE",icon:"🪸",tier:"FREE",desc:"Aprenda o ritmo entre corais, moedas e passagens largas.",mission:"Chegue ao final • preserve suas vidas",goal:32,gap:.27,speed:2.55,colors:["#6ae7f1","#087ca2"],mechanic:"coral"},
{name:"CORRENTEZA",short:"CORRENTEZA",icon:"🌊",tier:"FREE",desc:"A água acelera e os obstáculos começam a se mover.",mission:"Domine a correnteza • prepare-se para as profundezas",goal:39,gap:.235,speed:3.05,colors:["#238fd1","#073b76"],mechanic:"current"},
{name:"NAVIO AFUNDADO",short:"NAVIO",icon:"⚓",tier:"PREMIUM",desc:"Com Puff Prime, atravesse destroços, mastros e correntes.",mission:"Explore o casco • sobreviva à pressão",goal:46,gap:.215,speed:3.55,colors:["#16778d","#03263e"],mechanic:"ship"},
{name:"ABISMO",short:"ABISMO",icon:"🌌",tier:"PREMIUM",desc:"Escuridão, velocidade máxima e precisão. A jornada final.",mission:"Conquiste o Abismo • finalize a jornada",goal:54,gap:.20,speed:4.0,colors:["#102f72","#030817"],mechanic:"abyss"}];

let ac=null,musicTimer=null;
function audio(){if(!soundOn)return null;if(!ac)ac=new (window.AudioContext||window.webkitAudioContext)();if(ac.state==="suspended")ac.resume();return ac}
function tone(freq=440,dur=.08,type="sine",vol=.035,delay=0){let a=audio();if(!a)return;let o=a.createOscillator(),g=a.createGain(),t=a.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+dur)}
function sfx(k){if(!soundOn)return;if(k==="flap")tone(330,.045,"sine",.018);if(k==="coin"){tone(760,.07,"sine",.03);tone(1040,.08,"sine",.02,.04)}if(k==="hit")tone(105,.16,"sawtooth",.035);if(k==="win"){[523,659,784,1047].forEach((n,i)=>tone(n,.22,"triangle",.035,i*.11))}if(k==="unlock"){[330,440,660,880].forEach((n,i)=>tone(n,.28,"triangle",.03,i*.12))}}
function musicStart(){musicStop();if(!soundOn)return;let seq=stage<2?[220,277,330,277]:[147,196,220,294],i=0;musicTimer=setInterval(()=>{if(running)tone(seq[i++%seq.length],.28,"sine",.009)},360)}
function musicStop(){clearInterval(musicTimer);musicTimer=null}
function resize(){D=Math.min(devicePixelRatio||1,2);W=C.clientWidth;H=C.clientHeight;C.width=W*D;C.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener("resize",resize,{passive:true});resize();
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function screen(id){screens.forEach(s=>$("#"+s).classList.toggle("hidden",s!==id));$("#hud").classList.add("hidden")}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1200)}
function persist(){best=Math.max(best,score);localStorage.pr375best=best;localStorage.pr375bank=bank;localStorage.pr375unlock=unlocked;localStorage.pr375stars=JSON.stringify(stars);localStorage.pr375premium=premium?"1":"0";localStorage.pr375sound=soundOn?"1":"0";homeStats()}
function homeStats(){$("#best").textContent=best;$("#bank").textContent=bank;$("#starsBank").textContent=stars.reduce((a,b)=>a+b,0);$("#continueBtn").textContent=unlocked?"CONTINUAR JORNADA":"COMEÇAR JORNADA";$("#soundBtn").textContent=soundOn?"🔊 SOM":"🔇 SOM"}
function mapDraw(){let h="";STAGES.forEach((s,i)=>{let paid=i>=2,lock=i>unlocked||(paid&&!premium);h+=`<div class="stageCard ${paid?"premiumStage":""} ${lock?"locked":""}" data-i="${i}"><span class="medal">${"⭐".repeat(stars[i])}</span><div class="ico">${s.icon}${lock?" 🔒":""}</div><b>${i+1}. ${s.name}</b><small>${s.tier} • ${s.desc}</small></div>`});$("#stageCards").innerHTML=h;document.querySelectorAll(".stageCard").forEach(e=>e.onclick=()=>{let i=+e.dataset.i;if(i>=2&&!premium){screen("premium");return}if(i<=unlocked)intro(i)})}
function intro(i){if(i>=2&&!premium){screen("premium");return}stage=i;let s=STAGES[i];$("#introIcon").textContent=s.icon;$("#introTitle").textContent=s.name;$("#introDesc").textContent=s.desc;$("#introMission").textContent="MISSÃO • "+s.mission;let b=$("#tierBadge");b.textContent=s.tier;b.className="tier "+(i<2?"free":"paid");screen("intro")}
function resetStage(){let s=STAGES[stage];score=0;coins=0;lives=3;distance=0;spawn=45;pickSpawn=55;powerSpawn=300;inv=0;combo=0;obs=[];items=[];fx=[];fish={x:W*.24,y:H*.45,v:0,r:21};running=true;screens.forEach(q=>$("#"+q).classList.add("hidden"));$("#hud").classList.remove("hidden");sync();musicStart()}
function sync(){let s=STAGES[stage];$("#stageName").textContent=s.short;$("#score").textContent=score;$("#coins").textContent=coins;$("#lives").textContent=lives;$("#progress").textContent=Math.min(100,Math.floor(distance/s.goal*100))+"%"}
function speed(){return STAGES[stage].speed+Math.min(distance,55)*(.008+stage*.0015)}
function flap(){if(!running)return;audio();fish.v=-6.15;sfx("flap");for(let i=0;i<5;i++)fx.push({x:fish.x-18,y:fish.y+rnd(-8,8),vx:rnd(-2.2,-.6),vy:rnd(-.8,.8),life:1})}
function addObs(){let s=STAGES[stage],gap=Math.max(122,H*s.gap),top=rnd(75,Math.max(85,H-gap-145));obs.push({x:W+70,top,gap,w:rnd(58,73),passed:false,t:rnd(0,6),wob:stage?rnd(2,stage*4+3):0})}
function addItem(type="coin"){items.push({type,x:W+35,y:rnd(90,H-105),r:type==="coin"?9:13,t:rnd(0,6)})}
function hit(o){let top=o.top+Math.sin(o.t)*o.wob;return fish.x+fish.r-5>o.x&&fish.x-fish.r+5<o.x+o.w&&(fish.y-fish.r+5<top||fish.y+fish.r-5>top+o.gap)}
function damage(){if(inv>0)return;lives--;inv=100;combo=0;sfx("hit");toast(lives?"💥 CUIDADO!":"💥 FIM DA TENTATIVA");sync();if(lives<=0)fail()}
function fail(){running=false;musicStop();bank+=coins;persist();$("#gameoverText").innerHTML=`Você chegou a <b>${Math.floor(distance/STAGES[stage].goal*100)}%</b> de ${STAGES[stage].name}.<br>Moedas salvas: <b>${coins}</b>.`;screen("gameover")}
function finish(){running=false;musicStop();sfx("win");let s=STAGES[stage],rating=lives===3&&coins>=8?3:lives>=2?2:1;stars[stage]=Math.max(stars[stage],rating);bank+=coins;if(stage===0)unlocked=Math.max(unlocked,1);if(stage===2)unlocked=Math.max(unlocked,3);persist();$("#completeTitle").textContent=s.name;$("#stars").textContent="★".repeat(rating)+"☆".repeat(3-rating);$("#completeText").innerHTML=`<b>${score} pontos</b> · ${coins} moedas · ${lives} vida${lives!==1?"s":""}<br>${rating===3?"PERFEITO! Você dominou esta fase.":"Fase vencida. Sua jornada continua."}`;$("#nextStage").textContent=stage===1?"DESCOBRIR AS PROFUNDEZAS":stage===3?"VER FINAL":"PRÓXIMA FASE";screen("complete")}
function update(dt){if(!running)return;let s=STAGES[stage];fish.v+=.335*dt;fish.y+=fish.v*dt;if(stage===1||stage===2)fish.y+=Math.sin(bg*.02)*.22*dt;spawn-=dt;pickSpawn-=dt;powerSpawn-=dt;inv=Math.max(0,inv-dt);comboT-=dt;if(comboT<=0)combo=0;if(spawn<=0){addObs();spawn=Math.max(55,100-stage*9)}if(pickSpawn<=0){addItem("coin");pickSpawn=rnd(62,105)}if(powerSpawn<=0){addItem("shield");powerSpawn=rnd(330,460)}let sp=speed()*dt;distance+=sp*.0085;if(distance>=s.goal){finish();return}for(const o of obs){o.x-=sp;o.t+=.028*dt;if(!o.passed&&o.x+o.w<fish.x){o.passed=true;score+=2;combo++;comboT=150;if(combo===5){score+=3;combo=0;toast("⚡ COMBO +3")}sync()}if(hit(o))damage()}for(const p of items){p.x-=sp*.92;p.t+=.07*dt;if(Math.hypot(p.x-fish.x,p.y-fish.y)<fish.r+p.r){p.dead=true;if(p.type==="coin"){coins++;score++;sfx("coin")}else{inv=330;toast("🛡️ ESCUDO ATIVO")}sync()}}obs=obs.filter(o=>o.x>-100);items=items.filter(p=>!p.dead&&p.x>-30);for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=.035*dt}fx=fx.filter(p=>p.life>0);if(fish.y-fish.r<0||fish.y+fish.r>H-27){damage();fish.y=clamp(fish.y,fish.r+3,H-51);fish.v=0}sync()}
function background(){let s=STAGES[stage],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,s.colors[0]);g.addColorStop(1,s.colors[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);bg+=speed()*.32;ctx.globalAlpha=.14;ctx.fillStyle="#fff";for(let i=0;i<14;i++){let bx=(i*91+bg*.14)%W,by=H-((i*79+bg*(.35+i%3*.1))%H);ctx.beginPath();ctx.arc(bx,by,2+i%4,0,7);ctx.fill()}ctx.globalAlpha=1;if(stage===0){ctx.fillStyle="#16a985";for(let i=0;i<8;i++){let q=(i*90-bg*.5)%W;ctx.fillRect(q,H-66,5,40);ctx.beginPath();ctx.arc(q+3,H-68,11,0,7);ctx.fill()}ctx.fillStyle="#e1c674";ctx.fillRect(0,H-27,W,27)}if(stage===1){ctx.globalAlpha=.22;ctx.strokeStyle="#b9f7ff";ctx.lineWidth=3;for(let i=0;i<9;i++){let q=(i*85-bg*.8)%W;ctx.beginPath();ctx.moveTo(q,80+i*30);ctx.lineTo(q+50,80+i*30);ctx.stroke()}ctx.globalAlpha=1}if(stage===2){ctx.strokeStyle="#09283b";ctx.lineWidth=9;ctx.globalAlpha=.7;for(let i=0;i<5;i++){let q=(i*145-bg*.4)%W;ctx.beginPath();ctx.moveTo(q,0);ctx.lineTo(q-75,190);ctx.stroke()}ctx.fillStyle="#573d27";ctx.fillRect((W-bg*.55)%(W+240)-120,H-75,120,18);ctx.globalAlpha=1}if(stage===3){ctx.globalAlpha=.25;ctx.fillStyle="#5b7cff";for(let i=0;i<7;i++){let q=(i*110-bg*.18)%W;ctx.beginPath();ctx.arc(q,H*.2+(i%4)*110,30+i*7,0,7);ctx.fill()}ctx.globalAlpha=1}}
function drawObs(o){let top=o.top+Math.sin(o.t)*o.wob,g=ctx.createLinearGradient(o.x,0,o.x+o.w,0);let mid=stage===3?"#253e89":stage===1?"#276ba7":"#187f8d";g.addColorStop(0,"#07384e");g.addColorStop(.5,mid);g.addColorStop(1,"#052b43");ctx.fillStyle=g;ctx.fillRect(o.x,0,o.w,top);ctx.fillRect(o.x,top+o.gap,o.w,H-top-o.gap-27);ctx.fillStyle=stage===3?"#667de1":"#36b7ad";ctx.fillRect(o.x-4,top-13,o.w+8,13);ctx.fillRect(o.x-4,top+o.gap,o.w+8,13)}
function drawItem(p){ctx.save();ctx.translate(p.x,p.y);let k=1+Math.sin(p.t)*.12;ctx.scale(k,k);ctx.shadowBlur=18;ctx.shadowColor=p.type==="coin"?"#ffe35b":"#92f6ff";ctx.fillStyle=p.type==="coin"?"#ffd43c":"#a7f7ff";ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.restore()}
function drawFish(){let prime=stage>=2;ctx.save();ctx.translate(fish.x,fish.y);ctx.rotate(clamp(fish.v*.05,-.3,.55));ctx.globalAlpha=inv>0&&Math.floor(inv/8)%2?.5:1;ctx.fillStyle=prime?"#2f82df":"#70d9ec";ctx.beginPath();ctx.moveTo(-17,0);ctx.lineTo(-42,-16);ctx.lineTo(-37,17);ctx.closePath();ctx.fill();ctx.fillStyle=prime?"#175ab7":"#ffe264";ctx.beginPath();ctx.ellipse(0,0,27,22,0,0,7);ctx.fill();ctx.strokeStyle=prime?"#ffd45b":"#d5ae24";ctx.lineWidth=prime?3:2;for(let a=0;a<8;a++){let q=a*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(q)*20,Math.sin(q)*16);ctx.lineTo(Math.cos(q)*(prime?34:30),Math.sin(q)*(prime?27:24));ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(10,-7,7,0,7);ctx.fill();ctx.fillStyle="#082b3d";ctx.beginPath();ctx.arc(13,-7,3,0,7);ctx.fill();ctx.strokeStyle=prime?"#f2c649":"#8d6815";ctx.beginPath();ctx.arc(9,6,7,.1,2.8);ctx.stroke();if(prime){ctx.shadowBlur=16;ctx.shadowColor="#48caff";ctx.strokeStyle="#74ddff";ctx.beginPath();ctx.moveTo(-34,0);ctx.lineTo(-55,0);ctx.stroke()}if(inv>120){ctx.strokeStyle="#b7f7ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,35,0,7);ctx.stroke()}ctx.restore()}
function render(){background();for(const o of obs)drawObs(o);for(const p of items)drawItem(p);for(const p of fx){ctx.globalAlpha=p.life;ctx.fillStyle="#d8fbff";ctx.beginPath();ctx.arc(p.x,p.y,3,0,7);ctx.fill();ctx.globalAlpha=1}drawFish()}
function loop(t){let dt=Math.min(2,(t-last)/16.667||1);last=t;update(dt);render();requestAnimationFrame(loop)}
$("#continueBtn").onclick=()=>{audio();intro(Math.min(unlocked,premium?3:1))};$("#mapBtn").onclick=()=>{audio();mapDraw();screen("map")};$("#mapBack").onclick=()=>screen("home");$("#startStage").onclick=resetStage;$("#retry").onclick=resetStage;$("#goMap").onclick=()=>{mapDraw();screen("map")};$("#retryStage").onclick=resetStage;$("#nextStage").onclick=()=>{if(stage===1){screen("premium")}else if(stage===3){screen("ending")}else intro(stage+1)};$("#premiumHome").onclick=()=>screen("home");$("#premiumPreview").onclick=()=>{audio();premium=true;unlocked=Math.max(unlocked,2);persist();sfx("unlock");toast("👑 PREMIUM LIBERADO PARA TESTE");setTimeout(()=>intro(2),650)};$("#endingHome").onclick=()=>screen("home");$("#soundBtn").onclick=()=>{soundOn=!soundOn;if(!soundOn)musicStop();persist();if(soundOn){audio();tone(660,.08,"sine",.03)}};
C.addEventListener("pointerdown",flap,{passive:true});addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();flap()}});
document.addEventListener("visibilitychange",()=>{if(document.hidden&&running){running=false;musicStop();bank+=coins;persist();$("#gameoverText").innerHTML="Jogo pausado e moedas salvas.<br>Volte quando quiser.";screen("gameover")}});
fish={x:W*.24,y:H*.45,v:0,r:21};homeStats();mapDraw();requestAnimationFrame(loop);